#!/bin/bash
# Will compile and execute ARM assembly
# Run in WSL

if [[ "$OSTYPE" == "msys" ]]; then
  wsl ./integration
else
  npm run --silent integration > __program.s &&
  arm-linux-gnueabihf-gcc -static ./__program.s -o ./__out &&
  qemu-arm ./__out &&
  rm ./__out &&
  rm ./__program.s
fi